In [22]:
from data_processing import *

In [23]:
# Đọc file dữ liệu mùa giải hiện tại và chuyển vào dataframe
df_saved_name = 'EPL23-24.csv'
df_ml = pd.read_csv(df_saved_name)  # Đọc file CSV vào dataframe df_ml
# Điền giá trị 0 vào các ô bị thiếu
df_ml = df_ml.fillna(0)  # Điền giá trị 0 vào các ô trống trong dataframe df_ml

# Chọn các cột cần giữ lại
columns_to_keep = ['Time', 'Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTR', 'Referee', 'HTR']
df_keep = df_ml[columns_to_keep]  # Tạo dataframe df_keep chứa các cột đã chọn

# Chọn các cột cần chuẩn hóa
columns_to_scale = [col for col in df_ml.columns if col not in columns_to_keep]
df_scale = df_ml[columns_to_scale]  # Tạo dataframe df_scale chứa các cột cần chuẩn hóa

# Chuẩn hóa các cột đã chọn
scaled_np = preprocessing.scale(df_scale)  # Chuẩn hóa dữ liệu trong df_scale
scaled_df = pd.DataFrame(scaled_np, columns=df_scale.columns)  # Tạo dataframe mới từ dữ liệu đã chuẩn hóa

# Kết hợp các cột đã giữ lại và các cột đã chuẩn hóa
data = pd.concat([df_keep, scaled_df], axis=1)  # Kết hợp df_keep và scaled_df

# Chọn các cột mong muốn
desired_columns = ['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']
data = data.loc[:, desired_columns]  # Tạo dataframe data chỉ chứa các cột mong muốn
data

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Burnley,Man City,-1.319824,1.191927,A,-1.503528,0.882414,-1.539688,1.414263,0.073930,-0.912093,-0.038444,0.098819,-1.373769,-1.630966,3.546389,-0.288089
1,Arsenal,Nott'm Forest,0.146647,-0.375313,H,-0.064383,-1.132054,0.542452,-0.963701,0.363552,0.177829,0.583211,-0.590196,0.064336,-0.189647,-0.260469,-0.288089
2,Bournemouth,West Ham,-0.586588,-0.375313,D,-0.224288,0.699281,-0.151594,-0.567374,-0.505314,0.722790,1.204866,-0.245689,-0.654716,1.251671,-0.260469,-0.288089
3,Brighton,Luton,1.613118,-0.375313,H,1.854477,-0.582654,2.277570,-0.567374,0.073930,0.177829,-0.038444,0.787835,0.064336,-0.189647,-0.260469,-0.288089
4,Everton,Fulham,-1.319824,-0.375313,A,0.575237,-0.582654,1.236499,-0.963701,0.363552,-1.457054,1.204866,-0.245689,-1.373769,-0.189647,-0.260469,-0.288089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Crystal Palace,Aston Villa,2.346354,-1.158933,H,-0.064383,-0.765787,1.236499,-0.963701,-0.215692,-0.912093,-1.281755,-0.245689,-0.654716,1.251671,-0.260469,-0.288089
376,Liverpool,Wolves,0.146647,-1.158933,H,3.293622,-1.498321,2.971616,-0.567374,0.942795,-0.094651,1.204866,-0.934704,-0.654716,-0.910306,-0.260469,3.243321
377,Luton,Fulham,0.146647,1.975548,A,-0.064383,0.516147,0.195429,1.017935,1.232417,2.357673,-0.660100,-0.245689,2.221494,1.251671,-0.260469,-0.288089
378,Man City,West Ham,0.879883,-0.375313,H,2.014382,-1.681455,2.277570,-0.963701,-2.243044,0.177829,1.515693,-0.934704,-1.373769,-0.910306,-0.260469,-0.288089
379,Sheffield United,Tottenham,-1.319824,1.191927,A,-1.503528,1.065548,-1.539688,1.810590,0.073930,-0.639612,-1.281755,0.443327,0.064336,-1.630966,-0.260469,-0.288089

In [24]:
# Đọc file dữ liệu mùa giải trước và chuyển vào dataframe
last_season = 'EPL22-23.csv'
last_season = pd.read_csv(last_season)  # Đọc file CSV vào dataframe last_season

# Điền giá trị 0 vào các ô bị thiếu
last_season = last_season.fillna(0)  # Điền giá trị 0 vào các ô trống trong dataframe last_season

# Tính tỷ lệ thắng trên sân nhà của mỗi đội từ cột 'FTR' (Full Time Result)
home_win = last_season.groupby('HomeTeam')['FTR'].apply(lambda x: (x == 'H').mean())
# Tính tỷ lệ hòa trên sân nhà của mỗi đội từ cột 'FTR'
home_draw = last_season.groupby('HomeTeam')['FTR'].apply(lambda x: (x == 'D').mean())
# Tính tỷ lệ thắng trên sân khách của mỗi đội từ cột 'FTR'
away_win = last_season.groupby('AwayTeam')['FTR'].apply(lambda x: (x == 'A').mean())
# Tính tỷ lệ hòa trên sân khách của mỗi đội từ cột 'FTR'
away_draw = last_season.groupby('AwayTeam')['FTR'].apply(lambda x: (x == 'D').mean())

# Tạo DataFrame mới từ các Series trên
last_season_stats = pd.DataFrame({
    'LSHW': home_win,  # LSHW: Tỷ lệ thắng trên sân nhà mùa trước
    'LSHD': home_draw, # LSHD: Tỷ lệ hòa trên sân nhà mùa trước
    'LSAW': away_win,  # LSAW: Tỷ lệ thắng trên sân khách mùa trước
    'LSAD': away_draw  # LSAD: Tỷ lệ hòa trên sân khách mùa trước
}).reset_index()

# Đổi tên cột 'index' thành 'Team' để dễ dàng merge
last_season_stats.rename(columns={'index': 'Team'}, inplace=True)

last_season_stats

              Team      LSHW      LSHD      LSAW      LSAD
0          Arsenal  0.736842  0.157895  0.631579  0.157895
1      Aston Villa  0.631579  0.105263  0.315789  0.263158
2      Bournemouth  0.315789  0.210526  0.263158  0.105263
3        Brentford  0.526316  0.368421  0.263158  0.368421
4         Brighton  0.526316  0.210526  0.421053  0.210526
5          Chelsea  0.315789  0.368421  0.263158  0.210526
6   Crystal Palace  0.368421  0.368421  0.210526  0.263158
7          Everton  0.315789  0.157895  0.105263  0.473684
8           Fulham  0.421053  0.263158  0.368421  0.105263
9            Leeds  0.263158  0.368421  0.105263  0.157895
10       Leicester  0.263158  0.210526  0.210526  0.157895
11       Liverpool  0.684211  0.263158  0.315789  0.263158
12        Man City  0.894737  0.052632  0.578947  0.210526
13      Man United  0.789474  0.157895  0.421053  0.157895
14       Newcastle  0.578947  0.315789  0.421053  0.421053
15   Nott'm Forest  0.421053  0.315789  0.052632  0.263158
16     Southampton  0.105263  0.263158  0.210526  0.105263
17       Tottenham  0.631579  0.052632  0.315789  0.263158
18        West Ham  0.421053  0.210526  0.157895  0.157895
19          Wolves  0.473684  0.157895  0.105263  0.263158

In [25]:
teams = data['HomeTeam'].unique()
special_teams_map = {
    'Burnley': 'Leicester',
    'Sheffield United': 'Leeds',
    'Luton': 'Southampton'
}
home_l5m = dudoan_home_2_l5m(data,teams)
home_l5m=home_l5m[['Team','FTHG', 'HC', 'HF', 'HR', 'HS', 'HST', 'HY']]
home_l5m = home_l5m.merge(last_season_stats[['Team','LSHW', 'LSHD']],
                          left_on='Team', right_on='Team', how='left')

# Thay thế thông số của các đội đặc biệt bằng thông số của đội tương ứng
for team, replace_with in special_teams_map.items():
        replace_stats = last_season_stats.loc[last_season_stats['Team'] == replace_with, ['LSHW', 'LSHD', 'LSAW', 'LSAD']].iloc[0]
        home_l5m.loc[home_l5m['Team'] == team, ['LSHW', 'LSHD']] = replace_stats[['LSHW', 'LSHD']].values

away_l5m = dudoan_away_2_l5m(data,teams)
away_l5m=away_l5m[['Team','FTAG', 'AC', 'AF', 'AR', 'AS', 'AST', 'AY']]
away_l5m = away_l5m.merge(last_season_stats[['Team','LSAW', 'LSAD']],
                          left_on='Team', right_on='Team', how='left')

for team, replace_with in special_teams_map.items():
        replace_stats = last_season_stats.loc[last_season_stats['Team'] == replace_with, ['LSHW', 'LSHD', 'LSAW', 'LSAD']].iloc[0]   
        away_l5m.loc[away_l5m['Team'] == team, ['LSAW', 'LSAD']] = replace_stats[['LSHW', 'LSHD']].values

In [26]:
new_columns = {
    'Team': 'HomeTeam',
    'FTHG': 'FTHG_home',
    'HC': 'HC_home',
    'HF': 'HF_home',
    'HR': 'HR_home',
    'HS': 'HS_home',
    'HST': 'HST_home',
    'HY': 'HY_home',
    'LSHW': 'LSHW_home',
    'LSHD': 'LSHD_home'
}

home_l5m = home_l5m.rename(columns=new_columns)

new_columns = {
    'Team': 'AwayTeam',
    'FTAG': 'FTAG_away',
    'AC': 'AC_away',
    'AF': 'AF_away',
    'AR': 'AR_away',
    'AS': 'AS_away',
    'AST': 'AST_away',
    'AY': 'AY_away',
    'LSAW': 'LSAW_away',
    'LSAD': 'LSAD_away'
}

away_l5m = away_l5m.rename(columns=new_columns)

In [27]:
home_l5m

,HomeTeam,FTHG_home,HC_home,HF_home,HR_home,HS_home,HST_home,HY_home,LSHW_home,LSHD_home
0,Burnley,-4.399413e-01,-0.411438,0.421476,-0.260469,0.031560,-0.290404,-0.510906,0.263158,0.210526
1,Arsenal,4.399413e-01,-0.349272,0.363552,-0.260469,1.022971,0.334238,0.351957,0.736842,0.157895
2,Bournemouth,-4.440892e-17,0.334549,0.942795,-0.260469,-0.224288,-0.151594,0.351957,0.315789,0.210526
3,Brighton,-1.026530e+00,-0.038444,0.363552,-0.260469,-0.512117,-0.637427,-0.223285,0.526316,0.210526
4,Everton,-2.932942e-01,-0.535769,-0.331541,-0.260469,-0.288250,-0.498618,-0.367095,0.315789,0.157895
5,Sheffield United,-2.932942e-01,-0.224941,-0.099843,0.500902,-0.544098,-0.012785,0.208147,0.263158,0.368421
6,Newcastle,8.798827e-01,0.458880,-0.215692,0.500902,0.671180,0.473048,-0.798527,0.578947,0.315789
7,Brentford,-5.865885e-01,-0.162775,-0.679087,-0.260469,-0.480136,-0.498618,0.208147,0.526316,0.368421
8,Chelsea,1.466471e+00,0.210218,-0.737011,-0.260469,0.703161,1.236499,-0.367095,0.315789,0.368421
9,Man United,1.466471e-01,0.210218,-0.563238,-0.260469,0.479294,0.750666,-0.079474,0.789474,0.157895
10,Nott'm Forest,-1.466471e-01,-0.287107,0.247703,-0.260469,0.095522,-0.220999,-0.654716,0.421053,0.315789
11,Fulham,-5.865885e-01,-0.349272,-0.563238,0.500902,-0.799946,-0.568023,-0.367095,0.421053,0.263158
12,Liverpool,2.932942e-01,1.204866,0.595249,-0.260469,2.046363,1.583523,-0.223285,0.684211,0.263158
13,Wolves,-7.332356e-01,-0.349272,0.711098,-0.260469,-0.544098,-0.082190,1.214820,0.473684,0.157895
14,Tottenham,0.000000e+00,0.521045,0.537325,-0.260469,0.063541,-0.012785,0.351957,0.631579,0.052632
15,Man City,1.173177e+00,0.458880,-1.432103,-0.260469,1.310800,1.514118,-1.086148,0.894737,0.052632
16,Aston Villa,5.865885e-01,0.023721,0.247703,-0.260469,-0.416174,-0.429213,0.064336,0.631579,0.105263
17,West Ham,-2.932942e-01,0.334549,-0.273616,-0.260469,-0.096364,0.126024,-0.510906,0.421053,0.210526
18,Crystal Palace,1.319824e+00,-0.597934,0.016005,-0.260469,0.031560,0.681262,-0.079474,0.368421,0.368421
19,Luton,-2.932942e-01,-0.100610,0.305627,-0.260469,-0.288250,-0.012785,-0.223285,0.105263,0.263158

In [28]:
away_l5m

,AwayTeam,FTAG_away,AC_away,AF_away,AR_away,AS_away,AST_away,AY_away,LSAW_away,LSAD_away
0,Burnley,0.094859,-0.314590,-0.149147,1.124475,0.076627,0.383812,-0.045515,0.263158,0.210526
1,Arsenal,0.251583,0.167721,0.395814,-0.288089,0.333014,0.304546,-0.333779,0.631579,0.157895
2,Bournemouth,-0.532037,0.029918,0.504806,0.418193,0.406267,-0.171047,-0.189647,0.263158,0.105263
3,Brighton,-0.688761,-0.245689,-0.258139,-0.288089,0.735908,-0.012516,0.098617,0.421053,0.210526
4,Everton,-0.532037,0.236623,0.668294,-0.288089,-0.692534,-0.725905,0.531012,0.105263,0.473684
5,Sheffield United,-0.532037,-0.107885,-0.367132,-0.288089,-0.253013,-0.567374,-0.910306,0.263158,0.368421
6,Newcastle,0.565031,0.098819,-0.149147,-0.288089,0.516147,0.859405,0.386880,0.421053,0.421053
7,Brentford,0.565031,0.443327,0.232325,0.418193,-0.069880,0.304546,0.098617,0.263158,0.368421
8,Chelsea,0.251583,0.029918,0.014341,0.418193,-0.069880,-0.171047,0.386880,0.263158,0.210526
9,Man United,0.094859,-0.452393,0.177829,-0.288089,-0.179760,-0.329577,-0.766175,0.421053,0.157895
10,Nott'm Forest,-0.061865,-0.314590,-0.367132,-0.288089,0.113254,0.225281,-0.477911,0.052632,0.263158
11,Fulham,0.408307,0.856737,0.177829,-0.288089,1.065548,0.780139,-0.477911,0.368421,0.105263
12,Liverpool,0.408307,1.132343,0.123333,-0.288089,1.688202,1.097201,-0.477911,0.315789,0.263158
13,Wolves,-0.532037,-0.865803,0.668294,0.418193,-0.839041,-0.725905,0.386880,0.105263,0.263158
14,Tottenham,-0.218589,0.167721,0.068837,-0.288089,0.406267,0.146015,0.242748,0.315789,0.263158
15,Man City,1.348651,0.374426,-1.511550,-0.288089,0.223134,0.859405,-1.054438,0.578947,0.210526
16,Aston Villa,-0.532037,0.236623,-0.367132,-0.288089,-0.692534,-0.725905,-0.045515,0.315789,0.263158
17,West Ham,0.094859,-0.521295,-0.585116,-0.288089,-0.729161,-0.725905,-0.333779,0.157895,0.157895
18,Crystal Palace,-0.218589,-0.176787,0.341318,0.418193,-0.472774,-0.408843,-0.477911,0.210526,0.263158
19,Luton,-0.532037,-0.383492,0.014341,-0.288089,-1.168681,-0.725905,-0.333779,0.105263,0.263158

In [79]:
import joblib
import pandas as pd

# Load model từ file
loaded_model = joblib.load('best_random_forest.joblib')

home_l5m_copy=home_l5m.copy()
away_l5m_copy=away_l5m.copy()

# Mã hóa tên đội thành số
home_l5m['HomeTeam_code'] = home_l5m['HomeTeam'].astype('category').cat.codes 
away_l5m['AwayTeam_code'] = away_l5m['AwayTeam'].astype('category').cat.codes

# Tạo dictionary để map tên đội với mã số
home_team_dict = dict(zip(home_l5m['HomeTeam'], home_l5m_copy['HomeTeam_code']))
away_team_dict = dict(zip(away_l5m['AwayTeam'], away_l5m_copy['AwayTeam_code']))

# Nhập tên đội nhà và đội khách
home_team = input("Nhập tên đội nhà: ")
away_team = input("Nhập tên đội khách: ")

# Lấy mã số của đội nhà và đội khách
home_team_code = home_team_dict[home_team]
away_team_code = away_team_dict[away_team]

# Lấy thông tin đội nhà và đội khách dựa trên mã số
home_info = home_l5m[home_l5m['HomeTeam_code'] == home_team_code].iloc[0]
away_info = away_l5m[away_l5m['AwayTeam_code'] == away_team_code].iloc[0]

# Tạo dataframe đầu vào cho model
input_data = pd.DataFrame({
    'HomeTeam': [home_info['HomeTeam_code']],
    'AwayTeam': [away_info['AwayTeam_code']],
    'AC_away': [away_info['AC_away']],
    'AF_away': [away_info['AF_away']],
    'AR_away': [away_info['AR_away']],
    'AS_away': [away_info['AS_away']],
    'AST_away': [away_info['AST_away']],
    'AY_away': [away_info['AY_away']],
    'FTAG_away': [away_info['FTAG_away']],
    'FTHG_home': [home_info['FTHG_home']],
    'HC_home': [home_info['HC_home']],
    'HF_home': [home_info['HF_home']],
    'HR_home': [home_info['HR_home']],
    'HS_home': [home_info['HS_home']],
    'HST_home': [home_info['HST_home']],
    'HY_home': [home_info['HY_home']],
    'LSHW_home': [home_info['LSHW_home']],
    'LSHD_home': [home_info['LSHD_home']],
    'LSAW_away': [away_info['LSAW_away']],
    'LSAD_away': [away_info['LSAD_away']]
})

# Dự đoán kết quả
prediction = loaded_model.predict(input_data)

# In kết quả
result = ""
if prediction[0] == 2:
    result = "thắng"
elif prediction[0] == 0:
    result = "thua"
else:
    result = "hòa"
print("Kết quả dự đoán trận đấu giữa", home_team, "và", away_team, "là:", result)

Kết quả dự đoán trận đấu giữa Wolves và Man City là: thua

In [56]:
input_data

,HomeTeam,AwayTeam,AC_away,AF_away,AR_away,AS_away,AST_away,AY_away,FTAG_away,FTHG_home,HC_home,HF_home,HR_home,HS_home,HST_home,HY_home,LSHW_home,LSHD_home,LSAW_away,LSAD_away
0,12,13,-0.452393,0.177829,-0.288089,-0.17976,-0.329577,-0.766175,0.094859,1.173177,0.45888,-1.432103,-0.260469,1.3108,1.514118,-1.086148,0.894737,0.052632,0.421053,0.157895