**Xử lí dữ liệu**

In [1]:
import sys
sys.path.append('/workspaces/match_football_prediction/utils')

In [2]:
import numpy as np
import pandas as pd
from data_processing import *

In [3]:
# Đọc file dữ liệu mùa giải hiện tại và chuyển vào dataframe
df_saved_name = '/workspaces/match_football_prediction/dulieuhuanluyen/EPL23-24.csv'
df_ml = pd.read_csv(df_saved_name)  # Đọc file CSV vào dataframe df_ml
df_ml

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,19/05/2024,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,...,2.78,-0.75,1.73,2.08,1.78,2.16,1.93,2.21,1.81,2.05
376,E0,19/05/2024,16:00,Liverpool,Wolves,2,0,H,2,0,...,5.17,-2.75,2.07,1.86,2.04,1.85,2.10,1.89,2.04,1.82
377,E0,19/05/2024,16:00,Luton,Fulham,2,4,A,1,2,...,2.69,0.25,2.00,1.93,1.99,1.93,2.02,1.94,1.96,1.91
378,E0,19/05/2024,16:00,Man City,West Ham,3,1,H,2,1,...,4.82,-3.00,2.03,1.90,1.99,1.90,2.05,1.99,1.96,1.91
379,E0,19/05/2024,16:00,Sheffield United,Tottenham,0,3,A,0,1,...,3.81,1.50,2.06,1.87,2.05,1.88,2.08,1.89,2.01,1.86

In [4]:
# Điền giá trị 0 vào các ô bị thiếu
data = df_ml.fillna(0)  # Điền giá trị 0 vào các ô trống trong dataframe df_ml

# Chọn các cột mong muốn
desired_columns = ['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']
data = data.loc[:, desired_columns]  # Tạo dataframe data chỉ chứa các cột mong muốn
data

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Burnley,Man City,0,3,A,6,17,1,8,11,8,6,5,0,0,1,0
1,Arsenal,Nott'm Forest,2,1,H,15,6,7,2,12,12,8,3,2,2,0,0
2,Bournemouth,West Ham,1,1,D,14,16,5,3,9,14,10,4,1,4,0,0
3,Brighton,Luton,4,1,H,27,9,12,3,11,12,6,7,2,2,0,0
4,Everton,Fulham,0,1,A,19,9,9,2,12,6,10,4,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Crystal Palace,Aston Villa,5,0,H,15,8,9,2,10,8,2,4,1,4,0,0
376,Liverpool,Wolves,2,0,H,36,4,14,3,14,11,10,2,1,1,0,1
377,Luton,Fulham,2,4,A,15,15,6,7,15,20,4,4,5,4,0,0
378,Man City,West Ham,3,1,H,28,3,12,2,3,12,11,2,0,1,0,0
379,Sheffield United,Tottenham,0,3,A,6,18,1,9,11,9,2,6,2,0,0,0

In [5]:
# Đọc file dữ liệu mùa giải trước và chuyển vào dataframe
last_season = '/workspaces/match_football_prediction/dulieuhuanluyen/EPL22-23.csv'
last_season = pd.read_csv(last_season)  # Đọc file CSV vào dataframe last_season

# Điền giá trị 0 vào các ô bị thiếu
last_season = last_season.fillna(0)  # Điền giá trị 0 vào các ô trống trong dataframe last_season

# Tính tỷ lệ thắng trên sân nhà của mỗi đội từ cột 'FTR' (Full Time Result)
home_win = last_season.groupby('HomeTeam')['FTR'].apply(lambda x: (x == 'H').mean())
# Tính tỷ lệ hòa trên sân nhà của mỗi đội từ cột 'FTR'
home_draw = last_season.groupby('HomeTeam')['FTR'].apply(lambda x: (x == 'D').mean())
# Tính tỷ lệ thắng trên sân khách của mỗi đội từ cột 'FTR'
away_win = last_season.groupby('AwayTeam')['FTR'].apply(lambda x: (x == 'A').mean())
# Tính tỷ lệ hòa trên sân khách của mỗi đội từ cột 'FTR'
away_draw = last_season.groupby('AwayTeam')['FTR'].apply(lambda x: (x == 'D').mean())

# Tạo DataFrame mới từ các Series trên
last_season_stats = pd.DataFrame({
    'LSHW': home_win,  # LSHW: Tỷ lệ thắng trên sân nhà mùa trước
    'LSHD': home_draw, # LSHD: Tỷ lệ hòa trên sân nhà mùa trước
    'LSAW': away_win,  # LSAW: Tỷ lệ thắng trên sân khách mùa trước
    'LSAD': away_draw  # LSAD: Tỷ lệ hòa trên sân khách mùa trước
}).reset_index()

# Đổi tên cột 'index' thành 'Team' để dễ dàng merge
last_season_stats.rename(columns={'index': 'Team'}, inplace=True)

last_season_stats

              Team      LSHW      LSHD      LSAW      LSAD
0          Arsenal  0.736842  0.157895  0.631579  0.157895
1      Aston Villa  0.631579  0.105263  0.315789  0.263158
2      Bournemouth  0.315789  0.210526  0.263158  0.105263
3        Brentford  0.526316  0.368421  0.263158  0.368421
4         Brighton  0.526316  0.210526  0.421053  0.210526
5          Chelsea  0.315789  0.368421  0.263158  0.210526
6   Crystal Palace  0.368421  0.368421  0.210526  0.263158
7          Everton  0.315789  0.157895  0.105263  0.473684
8           Fulham  0.421053  0.263158  0.368421  0.105263
9            Leeds  0.263158  0.368421  0.105263  0.157895
10       Leicester  0.263158  0.210526  0.210526  0.157895
11       Liverpool  0.684211  0.263158  0.315789  0.263158
12        Man City  0.894737  0.052632  0.578947  0.210526
13      Man United  0.789474  0.157895  0.421053  0.157895
14       Newcastle  0.578947  0.315789  0.421053  0.421053
15   Nott'm Forest  0.421053  0.315789  0.052632  0.263158
16     Southampton  0.105263  0.263158  0.210526  0.105263
17       Tottenham  0.631579  0.052632  0.315789  0.263158
18        West Ham  0.421053  0.210526  0.157895  0.157895
19          Wolves  0.473684  0.157895  0.105263  0.263158

In [6]:
# Lấy danh sách các đội từ cột 'HomeTeam' trong dữ liệu
teams = data['HomeTeam'].unique()
# Chuẩn bị tập dữ liệu cho đội khách
prepare_dataset_away = prepare_dataset_away_l10m(data, teams) #train voi 10 tran truoc
# prepare_dataset_away = prepare_dataset_away_l5m(data, teams)
# Điền các giá trị NaN bằng 0
prepare_dataset_away = prepare_dataset_away.fillna(0)
# Chuẩn bị tập dữ liệu cho đội nhà
prepare_dataset_home = prepare_dataset_home_l10m(data, teams) #train voi 10 tran truoc
# prepare_dataset_home = prepare_dataset_home_l5m(data, teams)
# Điền các giá trị NaN bằng 0
prepare_dataset_home = prepare_dataset_home.fillna(0)


# Kết hợp hai dataframe lại thành một
merged_df = pd.merge(prepare_dataset_home,prepare_dataset_away, on=['FTR', 'HomeTeam', 'AwayTeam'], suffixes=('_away', '_home'))

# Chọn các cột cần thiết từ dataframe đã kết hợp
columns_away = ['FTAG_away','AC_away', 'AF_away', 'AR_away', 'AS_away', 'AST_away', 'AY_away']
columns_home = ['FTHG_home', 'HC_home', 'HF_home', 'HR_home', 'HS_home', 'HST_home', 'HY_home']
columns_to_group = ['FTR', 'HomeTeam', 'AwayTeam'] + columns_home+columns_away 

# Tạo dataframe mới và nhóm theo 'FTR', 'HomeTeam', 'AwayTeam'
new_df = merged_df[columns_to_group].groupby(['FTR', 'HomeTeam', 'AwayTeam']).mean().reset_index()
new_df['FTR'] = new_df['FTR'].astype('category').cat.codes
new_df

,FTR,HomeTeam,AwayTeam,FTHG_home,HC_home,HF_home,HR_home,HS_home,HST_home,HY_home,FTAG_away,AC_away,AF_away,AR_away,AS_away,AST_away,AY_away
0,0,Arsenal,Aston Villa,1.5,5.4,11.7,0.1,13.6,5.7,2.4,0.7,2.4,9.6,0.1,6.7,2.5,1.6
1,0,Arsenal,West Ham,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,Aston Villa,Man United,1.2,7.2,9.6,0.0,17.5,5.0,2.3,1.1,3.1,13.8,0.1,8.9,3.5,2.4
3,0,Aston Villa,Newcastle,2.2,4.9,12.7,0.0,16.7,6.8,2.3,0.8,3.0,13.8,0.1,8.4,3.2,2.7
4,0,Aston Villa,Tottenham,1.8,8.5,14.5,0.0,14.2,4.0,2.9,1.3,3.6,13.1,0.1,9.9,3.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2,Wolves,Fulham,2.0,4.7,8.9,0.0,17.1,6.3,1.6,1.2,5.4,11.1,0.0,12.5,3.9,3.1
376,2,Wolves,Luton,2.8,7.6,12.9,0.0,21.7,7.3,1.7,1.4,4.8,10.1,0.1,15.5,5.0,2.5
377,2,Wolves,Man City,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
378,2,Wolves,Sheffield United,2.5,8.6,8.5,0.1,16.0,5.9,1.4,1.3,5.4,11.9,0.0,13.6,4.3,3.4
379,2,Wolves,Tottenham,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
from sklearn.preprocessing import StandardScaler

df = new_df.copy()

# Merge `current_df_copy` với `last_season_stats` để lấy thông số cho đội nhà
df = df.merge(last_season_stats[['Team', 'LSHW', 'LSHD']], left_on='HomeTeam', right_on='Team', how='left')
df.rename(columns={'LSHW': 'LSHW_home', 'LSHD': 'LSHD_home'}, inplace=True)

# Merge `current_df_copy` với `last_season_stats` một lần nữa để lấy thông số cho đội khách
df = df.merge(last_season_stats[['Team', 'LSAW', 'LSAD']], left_on='AwayTeam', right_on='Team', how='left', suffixes=('', '_away'))
df.rename(columns={'LSAW': 'LSAW_away', 'LSAD': 'LSAD_away'}, inplace=True)

# Loại bỏ các cột 'Team' và 'Team_away' không cần thiết
df.drop(['Team', 'Team_away'], axis=1, inplace=True)

# Tạo một bản đồ thay thế cho các đội đặc biệt(thông số 3 đội xuống hạng mùa trước sẽ thay 3 đội lên hạng mùa này)
special_teams_map = {
    'Burnley': 'Leicester',
    'Sheffield United': 'Leeds',
    'Luton': 'Southampton'
}

# Thay thế thông số của các đội đặc biệt bằng thông số của đội tương ứng
for team, replace_with in special_teams_map.items():
    # Kiểm tra nếu đội thay thế tồn tại trong last_season_stats
        replace_stats = last_season_stats.loc[last_season_stats['Team'] == replace_with, ['LSHW', 'LSHD', 'LSAW', 'LSAD']].iloc[0]
        
        # Cập nhật thông số cho đội cần thay thế trong DataFrame hiện tại
        df.loc[df['HomeTeam'] == team, ['LSHW_home', 'LSHD_home']] = replace_stats[['LSHW', 'LSHD']].values
        df.loc[df['AwayTeam'] == team, ['LSAW_away', 'LSAD_away']] = replace_stats[['LSAW', 'LSAD']].values
# Mã hóa các biến phân loại
df['HomeTeam_code'] = df['HomeTeam'].astype('category').cat.codes 
df['AwayTeam_code'] = df['AwayTeam'].astype('category').cat.codes
# Tạo dictionary để map tên đội với mã số
team_dict = dict(zip(df['HomeTeam'], df['HomeTeam_code']))
df = df.drop(columns=['HomeTeam_code','AwayTeam_code'])
df['AwayTeam']=df['AwayTeam'].astype('category').cat.codes
df['HomeTeam']=df['HomeTeam'].astype('category').cat.codes 

desired_order = [
    'FTR', 'HomeTeam', 'AwayTeam','LSHW_home','LSAW_away','LSHD_home','LSAD_away','FTHG_home','FTAG_away','HC_home','AC_away','HF_home',
    'AF_away','HR_home','AR_away', 'HS_home','AS_away', 'HST_home', 'AST_away','HY_home','AY_away'
]

# Sắp xếp lại các cột theo thứ tự mong muốn
df = df.reindex(columns=desired_order)

# Giả sử df là dataframe của bạn
cols_to_scale = ['LSHW_home','LSAW_away', 'LSHD_home', 'LSAD_away','FTHG_home', 'FTAG_away', 'HC_home', 'AC_away', 'HF_home', 'AF_away', 
                 'HR_home', 'HS_home', 'AS_away', 'HST_home', 'AST_away', 'HY_home', 
                 'AY_away']

# Tạo scaler object
scaler = StandardScaler()

# Áp dụng scaling cho các cột chỉ định
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

df

,FTR,HomeTeam,AwayTeam,LSHW_home,LSAW_away,LSHD_home,LSAD_away,FTHG_home,FTAG_away,HC_home,...,HF_home,AF_away,HR_home,AR_away,HS_home,AS_away,HST_home,AST_away,HY_home,AY_away
0,0,0,1,1.284691,0.191514,-0.718787,0.346083,0.660625,-0.001932,0.768056,...,1.212560,0.733213,1.097822,0.1,0.805103,0.161237,1.135343,0.171025,1.417459,0.460319
1,0,0,18,1.284691,-0.853110,-0.718787,-0.718787,-0.888351,-0.858636,-0.901843,...,-0.929037,-0.932785,-0.512882,0.0,-0.913372,-0.907244,-0.902235,-0.892982,-0.903407,-0.898293
2,0,1,13,0.749403,0.887931,-1.251222,-0.718787,0.350829,0.487612,1.324689,...,0.828171,1.462087,-0.512882,0.1,1.297901,0.512082,0.885114,0.596628,1.320756,1.139626
3,0,1,14,0.749403,0.887931,-1.251222,1.943387,1.383480,0.120454,0.613436,...,1.395603,1.462087,-0.512882,0.1,1.196815,0.432345,1.528560,0.468947,1.320756,1.394366
4,0,1,17,0.749403,0.191514,-1.251222,0.346083,0.970420,0.732385,1.726702,...,1.725079,1.340608,-0.512882,0.1,0.880918,0.671557,0.527644,0.681749,1.900973,0.884886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2,19,9,-0.053529,0.539723,-0.718787,-1.251222,1.176950,0.609998,0.551588,...,0.700041,0.993525,-0.512882,0.0,1.247358,1.086192,1.349825,0.766869,0.643837,1.734019
376,2,19,11,-0.053529,-0.504902,-0.718787,-1.251222,2.003071,0.854771,1.448385,...,1.432211,0.819983,-0.512882,0.1,1.828607,1.564616,1.707295,1.235033,0.740540,1.224539
377,2,19,12,-0.053529,1.932555,-0.718787,-0.186352,-0.888351,-0.858636,-0.901843,...,-0.929037,-0.932785,-0.512882,0.0,-0.913372,-0.907244,-0.902235,-0.892982,-0.903407,-0.898293
378,2,19,16,-0.053529,-1.201318,-0.718787,-0.718787,1.693275,0.732385,1.757626,...,0.626824,1.132358,1.097822,0.0,1.108364,1.261614,1.206837,0.937111,0.450431,1.988759
379,2,19,17,-0.053529,0.191514,-0.718787,0.346083,-0.888351,-0.858636,-0.901843,...,-0.929037,-0.932785,-0.512882,0.0,-0.913372,-0.907244,-0.902235,-0.892982,-0.903407,-0.898293

In [8]:
team_dict

{'Arsenal': 0,
 'Aston Villa': 1,
 'Bournemouth': 2,
 'Brentford': 3,
 'Brighton': 4,
 'Burnley': 5,
 'Chelsea': 6,
 'Crystal Palace': 7,
 'Everton': 8,
 'Fulham': 9,
 'Liverpool': 10,
 'Luton': 11,
 'Man United': 13,
 'Newcastle': 14,
 "Nott'm Forest": 15,
 'Sheffield United': 16,
 'Tottenham': 17,
 'West Ham': 18,
 'Wolves': 19,
 'Man City': 12}

**Huấn luyện dữ liệu**

In [9]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from joblib import dump, load

In [10]:
# Định nghĩa các biến đặc trưng và biến mục tiêu
X = df.drop('FTR', axis=1)
y = df['FTR']

# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

*Random Forest*

In [11]:
from sklearn.ensemble import RandomForestClassifier
# Tạo một lưới tham số để tìm kiếm
param_grid = {
    'n_estimators': [100, 200],            # Số lượng cây trong rừng ngẫu nhiên
    'max_features': ['sqrt', None], # Số lượng đặc trưng tối đa được xem xét để tách tại mỗi node
    'max_depth': [None, 5, 10],  # Độ sâu tối đa của cây
    'min_samples_split': [5, 10],  # Số lượng mẫu tối thiểu cần thiết để tách một nút
    'min_samples_leaf': [2, 4],  # Số lượng mẫu tối thiểu cần thiết để là một nút lá
    'bootstrap': [True, False]             # Có sử dụng phương pháp bootstrap để lấy mẫu hay không
}

# Khởi tạo bộ phân loại RandomForest với hạt giống ngẫu nhiên cố định
rf = RandomForestClassifier(random_state=42)

# Khởi tạo GridSearchCV với xử lý lỗi
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=9, n_jobs=-1, verbose=0, scoring='accuracy')

# Huấn luyện GridSearchCV trên dữ liệu huấn luyện
grid_search.fit(X_train, y_train)

# Lấy các tham số tốt nhất và điểm số tốt nhất từ kết quả tìm kiếm
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)

# Dự đoán với mô hình tốt nhất
best_rf = grid_search.best_estimator_
# Lưu mô hình
dump(best_rf, 'best_random_forest.joblib')
# Để tải mô hình sau này
best_rf_loaded = load('best_random_forest.joblib')

# Sử dụng mô hình đã tải để dự đoán
y_pred_loaded = best_rf_loaded.predict(X_test)
# In báo cáo phân loại
print("Classification Report:")
print(classification_report(y_test, y_pred_loaded,zero_division=0))

# In ma trận nhầm lẫn
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_loaded))

# In độ chính xác
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred_loaded))

Best parameters found:  {'bootstrap': True, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 200}
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.42      0.49        33
           1       0.00      0.00      0.00         7
           2       0.56      0.75      0.64        36

    accuracy                           0.54        76
   macro avg       0.38      0.39      0.38        76
weighted avg       0.52      0.54      0.52        76

Confusion Matrix:
[[14  2 17]
 [ 3  0  4]
 [ 7  2 27]]
Accuracy Score:
0.5394736842105263

*K-NN*

In [12]:
# Import các thư viện cần thiết
from sklearn.neighbors import KNeighborsClassifier

# Định nghĩa lưới tham số cho GridSearchCV
param_grid = {
    'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41],  # Số lượng hàng xóm
    'weights': ['uniform', 'distance'],  # Trọng số cho các điểm lân cận
    'metric': ['euclidean', 'manhattan', 'minkowski'],  # Loại khoảng cách
    'p': [1, 2]  # Tham số cho khoảng cách Minkowski (1 là Manhattan, 2 là Euclidean)
}

# Khởi tạo bộ phân loại KNN
knn = KNeighborsClassifier()

# Khởi tạo GridSearchCV
grid_search = GridSearchCV(estimator=knn, param_grid=param_grid, cv=9, n_jobs=-1, verbose=0)

# Huấn luyện GridSearchCV trên dữ liệu huấn luyện
grid_search.fit(X_train, y_train)

# Lấy các tham số tốt nhất và điểm số tốt nhất từ kết quả tìm kiếm
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)

# Dự đoán với mô hình tốt nhất

best_knn = grid_search.best_estimator_

dump(best_knn, 'best_K_NN.joblib')
# Để tải mô hình sau này
best_knn_loaded = load('best_K_NN.joblib')

# Sử dụng mô hình đã tải để dự đoán
y_pred_loaded = best_knn_loaded.predict(X_test)

# In báo cáo phân loại
print("Classification Report:")
print(classification_report(y_test, y_pred_loaded,zero_division=0))

# In ma trận nhầm lẫn
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_loaded))

# In độ chính xác
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred_loaded))

Best parameters found:  {'metric': 'manhattan', 'n_neighbors': 33, 'p': 1, 'weights': 'uniform'}
Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.27      0.38        33
           1       0.00      0.00      0.00         7
           2       0.53      0.89      0.67        36

    accuracy                           0.54        76
   macro avg       0.39      0.39      0.35        76
weighted avg       0.53      0.54      0.48        76

Confusion Matrix:
[[ 9  1 23]
 [ 2  0  5]
 [ 3  1 32]]
Accuracy Score:
0.5394736842105263

*Decision Tree*

In [13]:
# Import các thư viện cần thiết
from sklearn.tree import DecisionTreeClassifier

# Định nghĩa lưới tham số cho GridSearchCV dành riêng cho Decision Tree
param_grid = {
    'criterion': ['gini', 'entropy'],  # Tiêu chuẩn để đánh giá việc tách nhánh
    'max_depth': [None, 5, 10, 15, 20],  # Độ sâu tối đa của cây
    'min_samples_split': [2, 5, 10],  # Số lượng mẫu tối thiểu cần thiết để tách một nút
    'min_samples_leaf': [1, 2, 4],  # Số lượng mẫu tối thiểu cần thiết để là một nút lá
    'max_features': ['sqrt', 'log2', None]  # Số lượng tính năng để xem xét khi tìm kiếm tách tốt nhất
}

# Khởi tạo bộ phân loại Decision Tree
dt = DecisionTreeClassifier(random_state=42)

# Khởi tạo GridSearchCV
grid_search = GridSearchCV(estimator=dt, param_grid=param_grid, cv=9, n_jobs=-1, verbose=0)

# Huấn luyện GridSearchCV trên dữ liệu huấn luyện
grid_search.fit(X_train, y_train)

# Lấy các tham số tốt nhất và điểm số tốt nhất từ kết quả tìm kiếm
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)

# Dự đoán với mô hình tốt nhất
best_dt = grid_search.best_estimator_


dump(best_dt, 'best_dt.joblib')
# Để tải mô hình sau này
best_dt_loaded = load('best_dt.joblib')

# Sử dụng mô hình đã tải để dự đoán
y_pred_loaded = best_dt_loaded.predict(X_test)

# In báo cáo phân loại
print("Classification Report:")
print(classification_report(y_test, y_pred_loaded,zero_division=0))

# In ma trận nhầm lẫn
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_loaded))

# In độ chính xác
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred_loaded))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 10}
Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.45      0.54        33
           1       0.06      0.14      0.09         7
           2       0.46      0.47      0.47        36

    accuracy                           0.43        76
   macro avg       0.39      0.36      0.36        76
weighted avg       0.51      0.43      0.46        76

Confusion Matrix:
[[15  3 15]
 [ 1  1  5]
 [ 7 12 17]]
Accuracy Score:
0.4342105263157895

*Naive_Bayes*

In [14]:
# Import các thư viện cần thiết
from sklearn.naive_bayes import GaussianNB

# Khởi tạo bộ phân loại Gaussian Naive Bayes
gnb = GaussianNB()  # Sử dụng giá trị phương sai đã chọn

# Huấn luyện mô hình trên dữ liệu huấn luyện
gnb.fit(X_train, y_train)


dump(gnb, 'best_gnb.joblib')
# Để tải mô hình sau này
gnb_loaded = load('best_gnb.joblib')

# Sử dụng mô hình đã tải để dự đoán
y_pred = gnb_loaded.predict(X_test)


# In báo cáo phân loại
print("Classification Report:")
print(classification_report(y_test, y_pred,zero_division=0))

# In ma trận nhầm lẫn
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# In độ chính xác
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.30      0.43        33
           1       0.11      0.43      0.17         7
           2       0.56      0.53      0.54        36

    accuracy                           0.42        76
   macro avg       0.46      0.42      0.38        76
weighted avg       0.58      0.42      0.46        76

Confusion Matrix:
[[10 11 12]
 [ 1  3  3]
 [ 3 14 19]]
Accuracy Score:
0.42105263157894735

*SVM*

In [15]:
from sklearn.svm import SVC

# Định nghĩa tham số grid cho GridSearchCV
param_grid = {
    'C': [0.1, 1, 10], 
    'gamma': [0.0001, 0.001, 0.01, 0.1],
    'kernel': ['rbf', 'linear']
}

# Khởi tạo mô hình SVM 
svm = SVC()

# Khởi tạo GridSearchCV với scoring phù hợp cho bài toán phân loại đa lớp
grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, cv=9, n_jobs=-1, scoring='accuracy')

# Huấn luyện mô hình với GridSearchCV
grid_search.fit(X_train, y_train)

# Lấy siêu tham số tốt nhất
best_params = grid_search.best_params_
print("Siêu tham số tốt nhất: ", best_params)

# Đánh giá mô hình với siêu tham số tốt nhất
best_svm = grid_search.best_estimator_

dump(best_svm, 'best_svm.joblib')
# Để tải mô hình sau này
best_svm_loaded = load('best_svm.joblib')

# Sử dụng mô hình đã tải để dự đoán
y_pred = best_svm_loaded.predict(X_test)

# In ra báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred,zero_division=0))

# In ra ma trận nhầm lẫn
print("Ma trận nhầm lẫn:")
print(confusion_matrix(y_test, y_pred))

# In ra độ chính xác
print("Độ chính xác:")
print(accuracy_score(y_test, y_pred))

Siêu tham số tốt nhất:  {'C': 1, 'gamma': 0.0001, 'kernel': 'linear'}
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       0.56      0.45      0.50        33
           1       0.00      0.00      0.00         7
           2       0.59      0.67      0.62        36

    accuracy                           0.51        76
   macro avg       0.38      0.37      0.37        76
weighted avg       0.52      0.51      0.51        76

Ma trận nhầm lẫn:
[[15  4 14]
 [ 4  0  3]
 [ 8  4 24]]
Độ chính xác:
0.5131578947368421